DROP TABLE COMPETICIONES CASCADE CONSTRAINTS;
DROP TABLE JORNADAS CASCADE CONSTRAINTS;
DROP TABLE JUGADORES CASCADE CONSTRAINTS;
DROP TABLE EQUIPOS CASCADE CONSTRAINTS;
DROP TABLE ENFRENTAMIENTOS CASCADE CONSTRAINTS;

CREATE TABLE COMPETICIONES (
    ID_COMPETICION NUMBER(4) PRIMARY KEY,
    NOMBRE VARCHAR2(20),
    ESTADO VARCHAR(20) CONSTRAINT com_est_ck CHECK(LOWER(ESTADO) IN('inscripcion', 'en curso', 'finalizada'))
);

CREATE TABLE JORNADAS (
    ID_JORNADA NUMBER(4) PRIMARY KEY,
    FECHA DATE,
    ID_COMPETICION NUMBER(4),
    CONSTRAINT jor_com_fk FOREIGN KEY (ID_COMPETICION) REFERENCES COMPETICIONES(ID_COMPETICION)
);

CREATE TABLE JUGADORES (
    ID_JUGADOR NUMBER(4) PRIMARY KEY,
    NOMBRE VARCHAR2(20),
    APELLIDO VARCHAR2(30),
    NACIONALIDAD VARCHAR2(30),
    FECHA_NAC DATE,
    NICKNAME VARCHAR2(20),
    SUELDO NUMBER(5),
    ID_EQUIPO NUMBER(4)
);

CREATE TABLE EQUIPOS (
    ID_EQUIPO NUMBER(4) PRIMARY KEY,
    NOMBRE VARCHAR2(20),
    FECHA_FUND DATE
);

ALTER TABLE JUGADORES ADD CONSTRAINT jug_equ_fk FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS(ID_EQUIPO);


CREATE TABLE ENFRENTAMIENTOS (
    ID_ENFRENTAMIENTO NUMBER(4) PRIMARY KEY,
    HORA DATE,
    FECHA_ENF DATE,
    EQUIPO_ATACANTE NUMBER(4),
    EQUIPO_DEFENSOR NUMBER(4),
    EQUIPO_GANADOR NUMBER(4),
    ID_JORNADA NUMBER(4),
    CONSTRAINT enf_atc_fk FOREIGN KEY (EQUIPO_ATACANTE) REFERENCES EQUIPOS(ID_EQUIPO),
    CONSTRAINT enf_def_fk FOREIGN KEY (EQUIPO_DEFENSOR) REFERENCES EQUIPOS(ID_EQUIPO),
    CONSTRAINT enf_gan_fk FOREIGN KEY (EQUIPO_GANADOR) REFERENCES EQUIPOS(ID_EQUIPO),
    CONSTRAINT enf_jor_fk FOREIGN KEY (ID_JORNADA) REFERENCES JORNADAS(ID_JORNADA)
);
